## DO NOT USE THIS FOR PRODUCTION, THX.
name: CI/CD
on: [push, pull_request]
jobs:
  # build:
  deploy:
    name: 'Deploy'
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && github.ref == 'refs/heads/master'
    # needs: build
    steps:
      - name: Configure SSH
        run: |
          mkdir -p ~/.ssh/
          echo "$SSH_KEY" > ~/.ssh/staging.key
          chmod 600 ~/.ssh/staging.key
          cat >>~/.ssh/config <<END
          Host staging
            HostName $SSH_HOST
            User $SSH_USER
            IdentityFile ~/.ssh/staging.key
            StrictHostKeyChecking no
          END
        env:
          SSH_USER: ${{ secrets.STAGING_SSH_USER }}
          SSH_KEY: ${{ secrets.STAGING_SSH_KEY }}
          SSH_HOST: ${{ secrets.STAGING_SSH_HOST }}

      - name: Stop the server
        run: ssh staging 'sudo docker stop viralatapp-backend && sudo docker rm viralatapp-backend'

      - name: Check out the source & build
        run: ssh staging 'cd /home/ec2-user/backend && sudo git fetch && sudo git reset --hard origin/master && sudo docker build -t viralatapp-backend .'

      - name: Start the server
        if: ${{ always() }}
        run: ssh staging 'sudo docker run --name viralatapp-backend -d -p 80:3000 viralatapp-backend'
